Fix minimal template, which was failing with:
C:\roundup>demo.py -t minimal
Traceback (most recent call last):
  File "C:\roundup\demo\schema.py", line 64, in <module>
    db.security.addPermissionToRole('Anonymous', 'Register', 'user')
  File "C:\roundup\roundup\security.py", line 304, in addPermissionToRole
    properties, check)
  File "C:\roundup\roundup\security.py", line 148, in getPermission
    raise ValueError, 'No permission "%s" defined'%permission
ValueError: No permission "Register" defined