Remove duplicate @csrf nonce from form. Duplicate nonce was causing:
File "/home/roundup/lib/python2.6/site-packages/roundup/cgi/client.py",
line 1154, in handle_csrf
 key=self.form['@csrf'].value
 AttributeError: 'list' object has no attribute 'value'

traceback.