Fix roundup-server logging for Python 3.
Using the roundup-server support for redirecting output to a log file
fails with Python 3:

    sys.stdout = sys.stderr = open(self["LOGFILE"], 'a', 0)
ValueError: can't have unbuffered text I/O

Thus, this patch switches that redirection to use line-buffered output
(1 as third argument to open), which works with both Python 2 and
Python 3.